### ISSUE TITLE
When object is rotated in the scene, gizmos do not also rotate

### ISSUE THREAD

**Issue by mjavaly** [mjavaly/Prairie#132] opened 2017-02-09 01:57 UTC
The gizmos seem to be very rigid. Is there a way to fix this?

**Comment by mjavaly** [comment] 2017-02-09 02:02
Here's a picture of the resulting scene editor: ![](https://cloud.githubusercontent.com/assets/7783266/22766140/6771f418-ee39-11e6-886f-36270740959d.png)

**Comment by grahamearley** [comment] 2017-02-09 03:11
Yeah, this was [one of my concerns with the gizmos stuff](https://github.com/mjavaly/Prairie/pull/45#issuecomment-271089844). I think we should just remove this particular gizmo.

**Comment by brennan724** [comment] 2017-02-09 03:18
Is it easy/quick to make the gizmo rotate?  If it is/doesn't take a lot of time, then it could be worth it.  Otherwise, I agree with Graham that exterminating is is the better way to go.

**Comment by grahamearley** [comment] 2017-02-09 03:19
Let's talk about this tomorrow.

I think it's not very helpful in the first place, since you only tumble objects in the actual game. When the gameplay is stopped, the object resets. So I don't think the gizmo is really telling you anything while you're just in the scene view.

**Comment by shoemakerc** [comment] 2017-02-09 03:20
I think way back when I was first toying around with Gizmos, one of the issues I had was trying to get meshes (what we see above) to rotate with the object in play mode.  As far as I know, there's no easy way to do so.

I'm all for removing it, unless one of us (Charlie) has an idea.  Regardless, we should talk about this tomorrow.

**Comment by cpimhoff** [comment] 2017-02-09 05:57
### Minor Gizmo Rant
I noticed that sometimes the Unity Editor doesn't really prioritize Gizmo drawing. Sometimes editing a value reflected in a Gizmo leads to immediate feedback via the Gizmo, sometimes it doesn't.

I've yet to be able to really pin down when Unity decides to actually update the Gizmos in real-time, and when it tosses Gizmos to a non-critical queue. But that's sort of unrelated.

### Actual Comment
More to the point here, I believe the problem is likely with our (re)drawing code not taking into account the set rotation of the object when we draw the Gizmo over it. We likely say "DrawMesh(mesh)" but forget that the mesh doesn't actually have rotation as part of it (its parent GameObject does).

We *could* fix this I'm sure. We're smart folks and this is probably as simple as also passing in the rotation vector into the call. However, I am a firm believer that this particular Gizmo isn't very useful, and would like to see us drop it rather than spend any more time worrying about it.

**Comment by shoemakerc** [comment] 2017-02-09 17:15
Resolved by PR #133

**Closed as completed by shoemakerc** 2017-02-09 17:15 UTC
Labels: user experience
